<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container06qMcTp\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container06qMcTp/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/Container06qMcTp.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\Container06qMcTp\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \Container06qMcTp\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => '06qMcTp',
    'container.build_id' => '7d98aad9',
    'container.build_time' => 1762798834,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container06qMcTp');
